### PR TITLE
"Fixed issue where perform_in would receive a Float when called by pe…

### PR DESCRIPTION
**Pull request by ahdbarjoud**
Fixed issue where perform_in would receive a Float when called by perform_at.

### CODE REVIEW

**Comment by ahdbarjoud** [comment]
I was trying to run the code below:
```cr
exec_at = Time.parse(env.params.json["execute_at"].to_s, "%m/%d/%Y, %H:%M:%S", Time::Location::UTC)
job = Availium::Scheduler::MyWorker.async.perform_at(exec_at, env.params.json["request_route"].to_s)
```
When I ran into this issue:
image info

I tried running specs but they kept breaking because of `require can not load such fuck - redis` error.

**Comment by hugopl** [comment]
Do you mind write a small rspec test for this? :grin: 

I didn't see the issue in detail, but is weird because in tests we have (api_spec.cr:107):

`job_id = ApiWorker.async.perform_in(100.seconds, 1_i64, "foo")`

that's basically the same thing, and the tests pass (with Crystal 0.36.1).

**Comment by hugopl** [comment]
nevermind... there's no calls to `perform_at` on tests...  so nothing weird here, I just got confused by `perform_at` vs `perform_in`.

**Comment by ahdbarjoud** [comment]
I'm confused (English learner), do you still want me to write specs for **perform_at**? Or is there something else would you like me to clarify/do.

**Comment by hugopl** [comment]
The fix is good, I was just asking if you would like to add some tests for the `perfotm_at` method to avoid future regressions. So both things (fix and tests) could be merged at once.

**Comment by ahdbarjoud** [comment]
I'm new to crystal, and I am having a lot of weird unrelated errors come up when running the specs. (Sorry)

**Comment by hugopl** [comment]
I did a fix for that, it was a bit different from yours, tests added as well. b6494c973f276b13288863f3bae406dff6a0f32a.

Thanks for the report and the patch!

**Pull request closed without merging**
