### PR TITLE
fix get REDIS_PROVIDER from ENV

### PR DESCRIPTION
**Pull request by icyleaf**
before:
```crystal
url = ENV[ENV["REDIS_PROVIDER"]]
```

after:

```crystal
url = ENV["REDIS_PROVIDER"]
```

### CODE REVIEW

**Comment by mperham** [comment]
You are not understanding how this feature works. REDIS_PROVIDER is not a URL, it is the name of the environment variable that contains the URL.  Your Redis provider will inject a variable like REDISTOGO_URL into your environment, you need to tell Sidekiq which environment variable to use.

**Comment by icyleaf** [comment]
Sorry about my short view, but why not use variables like ruby version to works instead get the variable from environment varibles?

**Comment by mperham** [comment]
I don't understand what you are asking, sorry.

1. You use Heroku.
2. You purchase Redis-to-Go.
3. Redis-to-Go sets REDISTOGO_URL in ENV.
4. You run `heroku config:set REDIS_PROVIDER=REDISTOGO_URL`.
5. Sidekiq knows to how to connect to Redis-to-Go.

**Comment by icyleaf** [comment]
Thanks for explain, i'm very interesting to Heroku but it's sadly to say, we can't access to visit the website because of G.F.W(aka great firewall) blocked it. 😭

**Comment by mperham** [comment]
You don't need to use Heroku.  You can do the same: put your Redis URL in REDIS_URL and set REDIS_PROVIDER=REDIS_URL

**Comment by icyleaf** [comment]
sorry for my poor english, i had not explain clearly. i got it from your first reply, the other ask is second question: load redis config from code, not only from the environment vaiables, like:

```crystal
cli = Sidekiq::CLI.new(args)
server = cli.configure do |config|
  config.redis = { "url" : "redis://localhost:6379/8" }
end
```

However sorry again to my naive questions

**Comment by mperham** [comment]
This is not Ruby, this is Crystal.  You don't want to recompile your binary to change the Redis location.

**Comment by icyleaf** [comment]
100% clear

**Pull request closed without merging**
