### PR TITLE
Enable Redis on Travis CI

### PR DESCRIPTION
**Pull request by jhass**
https://docs.travis-ci.com/user/database-setup/#Redis

### CODE REVIEW

**Comment by mperham** [comment]
No clue why this is still failing.  I'm using Redis 3.0 locally and it works fine.  The docs don't say anything about command argument changes. http://redis.io/commands/restore

**Comment by jhass** [comment]
> unless you use the REPLACE modifier (Redis 3.0 or greater)

I guess that tries to bring across that the `REPLACE` is new in 3.0.

**Comment by jhass** [comment]
We could workaround the missing `REPLACE` with issuing a `DEL` prior, next issue I get is that the dumps seem versioned, I have Redis 3.2 locally and get `RedisError: ERR DUMP payload version or checksum are wrong`

**Comment by mperham** [comment]
Good catch.  I assume they are using 2.8, which is pretty old by now but is Sidekiq's minimum supported version so the suite needs to pass on it.

**Pull request merged**
