### PR TITLE
Update to (yet to be released) Crystal 0.24

### PR DESCRIPTION
**Pull request by Sija**
SSIA

### CODE REVIEW

**Comment by Sija** [comment]
@mperham why?

**Comment by mperham** [comment]
I won’t accept PRs without a decent description.

**Comment by Sija** [comment]
What would be a _decent description_? This PR contains **one** commit with self-explanatory description, so... do you really need any more than this? IMHO you should be more interested in this PR than myself. Closing PRs without a word of explanation is certainly off-putting towards future contributions...

**Comment by duraki** [comment]
@mperham Come on mate, we can all fork. If you are decent enough to open source then at least you can merge request as these. Your lib is not up to date with developer requirements.

**Pull request closed without merging**
